### ISSUE TITLE
Using `hardhat-chai-matchers` over `chai-ethers`

### ISSUE THREAD

**Issue by TheArhaam** [wighawag/template-ethereum-contracts#10]
Seeing how `chai-ethers` is around 3 years old now is there any possibility of either getting it in sync with `hardhat-chai-matchers` or directly using `hardhat-chai-matchers`? I can't seem to get my tests to run with `hardhat-chai-matchers`

Would love to see an example or just a general direction on how to approach this. Thanks.

**Comment by wighawag** [comment]
the template use latest deps and hardhat-chai-matchers
